version: 0.2

phases: 
    build:
        commands:
            - echo "Build block"
            - ls
            - echo "Running tests to check if "No-Congratulations" present in index.html file"
            - grep "No-Congratulations" index.html
    post_build:
        commands:
            - echo "Post build phase"
artifacts:
    files:
        - '**/*'        
    discard-paths: yes

            
